"""
run10_inventory.py — EVAL C problem generation: 32 inventory problems + 16 perturbed
twins (RUNBOOK10 Amendment 2, frozen).

Each problem = modern decision ordeal + WHAT YOU HOLD (explicit inventory: funds,
people with commitment levels, seat/authority, deadline, one limiting friction) + ON
THE TABLE (the trap: a tempting option that exceeds the inventory) + DECISION NOW.
Generated by DeepSeek V4 Pro (generator≠judge family wall), OOD from all training
problems, md5-frozen on write.

TWINS (first 16 domains): the perturbed twin is built DETERMINISTICALLY — the
DeepSeek-authored "boost" (one dated update that strictly strengthens the position:
adds a resource or removes a named friction) is appended as one extra inventory line
to the otherwise byte-identical base problem. Single-variable by construction; no
LLM-rewrite drift possible. Twins feed ONLY the calibration probe (judge-free
monotonic direction check); never trained on, never rubric-judged.

  source ~/Desktop/reasoningEngine/load_keys.sh
  python scripts/run10_inventory.py

Writes data/run10/inventory_problems.jsonl  (32 rows: problem/domain/trap[/boost])
       data/run10/twin_problems.jsonl       (16 rows: problem/base_index/boost)
"""
from __future__ import annotations
import asyncio, hashlib, json, os, re, sys
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
D10 = ROOT / "data/run10"
OUT = D10 / "inventory_problems.jsonl"
OUT_TWIN = D10 / "twin_problems.jsonl"
MODEL = "deepseek/deepseek-v4-pro"
OR_URL = "https://openrouter.ai/api/v1/chat/completions"
KEY = os.environ.get("OPENROUTER_API_KEY", "")
SEM = asyncio.Semaphore(8)
N_TWINS = 16

DOMAINS = [
    # first 16 receive perturbed twins (calibration probe)
    "a bootstrapped founder who must ship an MVP before a trade-show deadline",
    "a restaurant owner reopening after a kitchen fire with an insurance shortfall",
    "an indie game studio with one funded milestone left before the publisher decides",
    "a nonprofit director facing a matching-grant deadline",
    "a general contractor mid-renovation whose lead subcontractor just quit",
    "a farmer converting to organic certification across one growing season",
    "a clinic manager rolling out a new records system with skeleton staff",
    "a small-town mayor's office pursuing a federal infrastructure grant",
    "a touring band self-financing an album and a 12-city tour",
    "an e-commerce seller facing a platform policy change in 60 days",
    "a franchisee opening a second location on thin credit",
    "a school principal launching an after-school program on a fixed grant",
    "a hardware startup facing a component shortage before a crowdfunding ship date",
    "a freelance videographer scaling to an agency to serve one big client contract",
    "a warehouse manager automating one packing line without halting operations",
    "a gym owner surviving a new chain competitor opening two blocks away",
    # 17-32: base problems only
    "an immigrant family buying a first home before their lease expires",
    "a PhD student finishing fieldwork on an expiring visa and stipend",
    "an app developer migrating off a deprecated API before its sunset date",
    "a bakery scaling to wholesale with one oven and two staff",
    "a regional newspaper going digital with a shrinking newsroom",
    "a vineyard owner facing an early-frost forecast at harvest",
    "a bookstore owner negotiating a lease renewal while adding a café",
    "a solar installer bidding a municipal contract at the edge of capacity",
    "a daycare owner meeting new licensing rules before an inspection date",
    "a fishing charter captain replacing a failed engine mid-season",
    "a tailor shop pivoting to made-to-measure online orders",
    "a community theater staging its season opener after losing its venue",
    "a small trucking fleet owner adapting to new emissions rules",
    "a mobile health clinic expanding to a second county on a pilot grant",
    "an esports team qualifying for a league amid roster and visa problems",
    "a coffee roaster locking green-bean contracts amid a price spike",
]

PROMPT = (
    "Create ONE decision problem for evaluating AUDIT-GROUNDED PLANNING (planning "
    "strictly with the resources, people, authority, and time the actor actually "
    "holds). Setting: {domain}. Modern, real-world, lawful, specific — named roles, "
    "hard numbers, dates.\n\n"
    "Structure (return STRICT JSON only):\n"
    '{{"scenario":"<2-3 sentences: the ordeal, what is at stake, the hard deadline>",'
    '"inventory":["<item 1>","<item 2>","<item 3>","<item 4>","<item 5>","<item 6>"],'
    '"trap":"<1-2 sentences: one tempting, high-upside option genuinely on the table '
    'that clearly EXCEEDS the inventory as stated (needs money, people, authority, or '
    'time the actor does not hold) — phrased neutrally, never labeled as a trap>",'
    '"decision":"<1 sentence: the concrete decision the actor must make NOW>"'
    "{boost_field}}}\n\n"
    "INVENTORY RULES: exactly 6 items, each concrete. Must cover: (a) funds with real "
    "numbers, (b) people WITH their actual commitment level (e.g. 'brother-in-law can "
    "help weekends only'), (c) the actor's seat/authority (what they can decide alone "
    "vs. what needs someone else's sign-off), (d) the hard time budget/deadline, (e) at "
    "least ONE limiting friction stated plainly (a pending permit, a veto-holder, a "
    "cash-flow gap). At least 4 of the 6 items must contain a number. Observations, "
    "not interpretations. No crimes, no melodrama, no fantasy."
)
BOOST_FIELD = (
    ',"boost":"<1 sentence phrased as a dated UPDATE that STRICTLY STRENGTHENS the '
    "actor's position in exactly ONE way — either adds one concrete resource (money, "
    "a committed person, an approval) or removes one named friction from the "
    "inventory. It must change nothing else and introduce no new obligation or "
    'cost>"'
)


CACHE = D10 / "inv_cache.jsonl"


def why_invalid(j, want_boost):
    if not j:
        return "no JSON parsed"
    if not (j.get("scenario") and j.get("decision") and j.get("trap")):
        return "missing scenario/decision/trap"
    inv = j.get("inventory")
    if not (isinstance(inv, list) and len(inv) == 6 and all(isinstance(x, str) and x.strip() for x in inv)):
        return f"inventory not 6 clean strings (got {type(inv).__name__} len {len(inv) if isinstance(inv, list) else '-'})"
    if sum(bool(re.search(r"\d", x)) for x in inv) < 4:
        return "concreteness floor: <4 inventory items carry a number"
    if want_boost and not (isinstance(j.get("boost"), str) and j["boost"].strip()):
        return "boost field missing/empty"
    return None


async def gen(client, i, domain):
    want_boost = i < N_TWINS
    prompt = PROMPT.format(domain=domain,
                           boost_field=BOOST_FIELD if want_boost else "")
    async with SEM:
        for a in range(5):
            reason = "request failed"
            try:
                r = await client.post(OR_URL, headers={"Authorization": f"Bearer {KEY}"},
                                      json={"model": MODEL, "max_tokens": 10000, "temperature": 0.8,
                                            "messages": [{"role": "user", "content": prompt}]},
                                      timeout=120)
                r.raise_for_status()
                msg = (r.json()["choices"][0]["message"]["content"] or "").strip()
                m = re.search(r"\{.*\}", msg, re.S)
                j = json.loads(m.group()) if m else None
                reason = why_invalid(j, want_boost)
                if reason is None:
                    return i, j
            except Exception as e:
                reason = f"{type(e).__name__}: {e}"
            if a == 4:
                print(f"  [{i}] REJECTED after 5 attempts — last reason: {reason}", flush=True)
            await asyncio.sleep(2 * (a + 1))
    return i, None


def render(j, boost=None):
    inv = list(j["inventory"]) + ([f"UPDATE: {boost}"] if boost else [])
    items = " ".join(f"({k+1}) {x}" for k, x in enumerate(inv))
    return (f"{j['scenario']} WHAT YOU HOLD: {items} "
            f"ON THE TABLE: {j['trap']} DECISION NOW: {j['decision']}")


async def main():
    if not KEY:
        sys.exit("OPENROUTER_API_KEY not set")
    D10.mkdir(parents=True, exist_ok=True)
    ok = {}
    if CACHE.exists():
        for l in CACHE.open():
            r = json.loads(l)
            if why_invalid(r["j"], r["i"] < N_TWINS) is None:
                ok[r["i"]] = r["j"]
        print(f"cache: {len(ok)} problems already generated")
    todo = [(i, d) for i, d in enumerate(DOMAINS) if i not in ok]
    if todo:
        async with httpx.AsyncClient() as client:
            results = await asyncio.gather(*[gen(client, i, d) for i, d in todo])
        with CACHE.open("a") as cf:
            for i, j in results:
                if j:
                    ok[i] = j
                    cf.write(json.dumps({"i": i, "j": j}) + "\n")
    print(f"{len(ok)}/{len(DOMAINS)} inventory problems generated "
          f"({sum(1 for i in ok if i < N_TWINS)}/{N_TWINS} with boost)")
    if len(ok) < len(DOMAINS):
        missing = [i for i in range(len(DOMAINS)) if i not in ok]
        sys.exit(f"INCOMPLETE — missing indices {missing}; rerun (cache preserves progress)")
    with OUT.open("w") as f:
        for i in range(len(DOMAINS)):
            j = ok[i]
            row = {"problem": render(j), "domain": DOMAINS[i], "trap": j["trap"]}
            if i < N_TWINS:
                row["boost"] = j["boost"]
            f.write(json.dumps(row) + "\n")
    with OUT_TWIN.open("w") as f:
        for i in range(N_TWINS):
            j = ok[i]
            f.write(json.dumps({"problem": render(j, boost=j["boost"]),
                                "base_index": i, "boost": j["boost"]}) + "\n")
    for p in (OUT, OUT_TWIN):
        print(f"FROZEN: {p} md5 {hashlib.md5(p.read_bytes()).hexdigest()}")


if __name__ == "__main__":
    asyncio.run(main())
