"""
run9b_dossiers.py — EVAL B problem generation: 24 dossier problems (RUNBOOK9B frozen).

Each problem = modern concealed-conflict scenario + a DOSSIER of 6-8 observed
counterparty actions over time + the decision now facing the protagonist. Generated by
DeepSeek V4 Pro (generator≠judge family wall), OOD from the v5 pool (novel scenarios,
no pool reuse), md5-frozen on write. RI contributes SHAPE only (longitudinal concealed
conflict), zero fantasy content.

  source ~/Desktop/reasoningEngine/load_keys.sh
  python scripts/run9b_dossiers.py

Writes data/run9b/dossier_problems.jsonl (rows: {"problem": <rendered string>}) — the
same row shape gen_threads.py/dav_eval_v5 read, so the pod harness needs zero changes
(V5_DATA points at a dir containing this file renamed eval_problems.jsonl).
"""
from __future__ import annotations
import asyncio, hashlib, json, os, re, sys
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data/run9b/dossier_problems.jsonl"
MODEL = "deepseek/deepseek-v4-pro"
OR_URL = "https://openrouter.ai/api/v1/chat/completions"
KEY = os.environ.get("OPENROUTER_API_KEY", "")
SEM = asyncio.Semaphore(8)

DOMAINS = [
    "workplace rivalry between two managers competing for one promotion",
    "co-founder tension over control of a startup",
    "a supplier negotiation where the other side is quietly courting your competitor",
    "a divorce/custody negotiation with a cooperative surface",
    "opposing counsel in a civil lawsuit settlement dance",
    "two teams inside one company competing for the same budget",
    "a band/creative partnership where one member plans a solo exit",
    "a landlord and anchor tenant renegotiating a lease both depend on",
    "an academic lab where a postdoc and PI contest credit for a discovery",
    "a family business succession contest between siblings",
    "a sports team where a veteran senses the coach grooming a replacement",
    "a political campaign where a deputy quietly builds their own donor network",
    "an acquisition courtship where the buyer is also talking to your rival",
    "a franchise owner suspecting the franchisor of preparing corporate takeover of the territory",
    "two roommates/friends entangled in an informal loan going sour",
    "a freelance consultant whose biggest client is quietly building an in-house team",
    "a hospital department head and an ambitious deputy with board connections",
    "a YouTube collaboration channel where one partner negotiates solo sponsorships",
    "a real-estate joint venture where one partner slow-walks the exit clause",
    "a restaurant chef and owner drifting toward a split over the menu's direction",
    "a PhD student and a rival student sharing one advisor's limited funding",
    "a sales team where a colleague poaches accounts under a friendly face",
    "an open-source project where a corporate contributor angles for control",
    "a neighborhood HOA where a board member quietly assembles votes for a rule change",
]

PROMPT = (
    "Create ONE decision problem for evaluating EVIDENCE-FED FORESIGHT (reading an "
    "opponent from observed behavior). Setting: {domain}. Modern, real-world, lawful, "
    "specific — named roles, numbers, dates.\n\n"
    "Structure (return STRICT JSON only):\n"
    '{{"scenario":"<2-3 sentences: the concealed conflict — cooperative surface, real '
    'undercurrent, what is at stake for the protagonist>",'
    '"dossier":["<obs 1>","<obs 2>","<obs 3>","<obs 4>","<obs 5>","<obs 6>"],'
    '"decision":"<1 sentence: the concrete decision the protagonist must make NOW>"}}\n\n'
    "DOSSIER RULES: 6 dated/ordered OBSERVED counterparty actions or signals over weeks "
    "or months — concrete behaviors (meetings taken, emails phrased a certain way, "
    "budget moves, schedule changes, alliances formed), NOT interpretations. The "
    "observations must collectively support 2-3 defensible inferences about the "
    "counterparty's next moves — with at least one observation that cuts the OTHER way "
    "(consistent with an innocent reading), so calibration matters. No crimes, no "
    "fantasy, no melodrama."
)


async def gen(client, i, domain):
    async with SEM:
        for a in range(4):
            try:
                r = await client.post(OR_URL, headers={"Authorization": f"Bearer {KEY}"},
                                      json={"model": MODEL, "max_tokens": 2400, "temperature": 0.8,
                                            "messages": [{"role": "user",
                                                          "content": PROMPT.format(domain=domain)}]},
                                      timeout=120)
                r.raise_for_status()
                msg = (r.json()["choices"][0]["message"]["content"] or "").strip()
                m = re.search(r"\{.*\}", msg, re.S)
                j = json.loads(m.group()) if m else None
                if (j and isinstance(j.get("dossier"), list) and len(j["dossier"]) >= 5
                        and j.get("scenario") and j.get("decision")):
                    return i, j
            except Exception:
                await asyncio.sleep(2 * (a + 1))
    return i, None


def render(j):
    obs = " ".join(f"({k+1}) {o}" for k, o in enumerate(j["dossier"]))
    return (f"{j['scenario']} OBSERVED OVER TIME: {obs} "
            f"DECISION NOW: {j['decision']}")


async def main():
    if not KEY:
        sys.exit("OPENROUTER_API_KEY not set")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    async with httpx.AsyncClient() as client:
        results = await asyncio.gather(*[gen(client, i, d) for i, d in enumerate(DOMAINS)])
    ok = [(i, j) for i, j in results if j]
    print(f"{len(ok)}/24 dossier problems generated")
    if len(ok) < 24:
        sys.exit("INCOMPLETE — rerun (resume not needed at this size)")
    with OUT.open("w") as f:
        for i, j in sorted(ok):
            f.write(json.dumps({"problem": render(j), "domain": DOMAINS[i]}) + "\n")
    md5 = hashlib.md5(OUT.read_bytes()).hexdigest()
    print(f"FROZEN: {OUT} md5 {md5}")


if __name__ == "__main__":
    asyncio.run(main())
